services:
  postgres:
    image: postgres:16-alpine
    container_name: aiserver-postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTRGES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: aiserver-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${POSTGRES_NAME}@example.com
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: